import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
    title: "My App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <div>
                    <Link href="/">Home</Link> | <Link href="/about">About</Link> | <Link href="/contact">Contact</Link> |{" "}
                    <Link href="/users">Users</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
